#!/bin/bash

declare -A MYTOOLS
JSON=$(curl -s https://api.github.com/repos/Jaynarol/bash-tools/contents/menu)

while read -r line; do
  if [[ $line =~ \"name\".*\"(.*)\" ]]; then
    name=${BASH_REMATCH[1]}
  elif [[ $line =~ \"download_url\".*\"(.*)\" ]]; then
    MYTOOLS[$name]=${BASH_REMATCH[1]}
  fi
done <<< "$JSON"

while : ; do
  PS3=$'\n'"##################################"$'\n'"Please select your tools... "$'\n'"0 to exit: "$'\n'"##################################"
  select i in "${!MYTOOLS[@]}"
  do
    [[ $choice -eq 0 ]] && break
    bash <(curl -s ${MYTOOLS[$i]})
    clear
    break
  done
done