#!/bin/bash

declare -A MYTOOLS
JSON=$(curl -s https://api.github.com/repos/Jaynarol/bash-tools/contents/menu)

while read -r line; do
  if [[ $line =~ \"name\".*\"(.*)\" ]]; then
    name=${BASH_REMATCH[1]}
  elif [[ $line =~ \"download_url\".*\"(.*)\" ]]; then
    MYTOOLS[$name]=${BASH_REMATCH[1]}
  fi
done <<< "$JSON"


clear
while : ; do
  printf "==================================\n"
  PS3=$'\n'"=================================="$'\n'"Please select your tools (0:exit): "
  select i in "${!MYTOOLS[@]}"
  do
    if [[ $i -eq 0 ]]; then
      exit
    fi
    bash <(curl -s ${MYTOOLS[$i]})
    clear
    break
  done
done