#!/bin/bash

export MY_SONAR_HOST
export MY_SONAR_TOKEN
export MY_DOCKER_HOST

IMAGE_NAME=''
CONTAINER_NAME=''
SONAR_KEY=''
SONAR_NAME=''
SONAR_VERSION=''


function main(){
  clear
  set_container_name
  while : ; do
    printf "\n\n[ q:exit | *:test-all | g:test-group | c:coverage | s:sonar | i:install | u:update | l:logs | m:make | h:ide-helper-model | e:exec ]\n\n"
    read -n1 -s
    case "$REPLY" in
	"i") clear; install           ;; 
	"g") clear; test_group        ;; 
	"s") clear; sonar             ;; 
	"u") clear; update            ;; 
	"c") clear; coverage          ;; 
	"e") clear; exec              ;; 
	"m") clear; make              ;; 
	"l") clear; logs              ;; 
	"h") clear; ide_helper_model  ;; 
	"q") clear; break             ;; 
	 * ) clear; test_all          ;; 
    esac
  done
}





function test_all(){
  if [ ! -z $CONTAINER_NAME ]; then
    run_container
    docker exec -it ${CONTAINER_NAME} vendor/bin/phpunit --no-coverage --exclude-group integration
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}


function test_group(){
  if [ ! -z $CONTAINER_NAME ]; then
    run_container
    read -p "Enter @group name for tests: " group_name
    while : ; do
      clear
      docker exec -it ${CONTAINER_NAME} vendor/bin/phpunit --no-coverage --group $group_name
      printf "\n\n[ q:exit | *:continue tests ($group_name) ]\n\n"
      read -n1 -s
      case "$REPLY" in
	"q") clear; break  ;; 
      esac
    done
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}


function coverage(){
  if [ ! -z $CONTAINER_NAME ]; then
    run_container
    docker exec -it ${CONTAINER_NAME} vendor/bin/phpunit --exclude-group integration
    start src/storage/phpunit/index.html
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}

function sonar(){
  if [ ! -z $CONTAINER_NAME ]; then
    run_container
    docker exec -it ${CONTAINER_NAME} vendor/bin/phpunit --exclude-group integration
    docker run --rm -v /$(pwd)/src:/var/www/html/ -e HOST=${MY_SONAR_HOST} -e TOKEN=${MY_SONAR_TOKEN} jaynarol/sonar-scanner
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}

function install(){
  if [ ! -d src ]; then
    set_project

    add_docker_compose
    add_gitignore
    add_nginx_conf
    set_container_name

    docker run --rm -v /$(pwd)/src:/var/www/html/ jaynarol/php-fpm-alpine:7.1-composer composer create-project --prefer-dist laravel/laravel .
    source src/.env
    rm -rf src/.env*
    sed -i "s@\[wait_key\]@$APP_KEY@" docker-compose.yml
    sed -i "s@\[wait_container\]@$CONTAINER_NAME@" docker-compose.yml

    add_phpunit
    add_sonar
  else
    printf "\n\n!!! The project has been installed !!!\n\n"
  fi
}

function update(){
  if [ -d src ]; then
    docker run --rm -v /$(pwd)/src:/var/www/html/ jaynarol/php-fpm-alpine:7.1-composer composer update
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}

function exec(){
  if [ ! -z $CONTAINER_NAME ]; then
    run_container
    docker exec -it $CONTAINER_NAME sh
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}

function make(){
  if [ ! -z $CONTAINER_NAME ]; then
    run_container
    read -p "php artisan make:" make_text
    docker exec -it ${CONTAINER_NAME} php artisan make:$make_text
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}

function ide_helper_model(){
  if [ ! -z $CONTAINER_NAME ]; then
    run_container
    docker exec -it ${CONTAINER_NAME} php artisan ide-helper:models
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}

function logs(){
  if [ ! -z $CONTAINER_NAME ]; then
    tail -f src/storage/logs/laravel.log
  else
    printf "\n\n!!! The project has not been installed !!!\n\n"
  fi
}



function run_container(){
  RUNNING=$(docker inspect --format="{{ .State.Running }}" ${CONTAINER_NAME} 2> /dev/null)
  if [ $? -eq 1 ] || [ "$RUNNING" == "false" ]; then
    docker-compose up -d
  fi
}

function set_project(){

    while [ -z $CONTAINER_NAME ]; do
        read -p "Enter DOCKER container name (ex: nova-api): " CONTAINER_NAME
    done

    while [ -z $SONAR_KEY ]; do
        read -p "Enter SONAR project key (ex: com.jaynarol.php.nova:api): " SONAR_KEY
    done

    while [ -z $SONAR_NAME ]; do
        read -p "Enter SONAR project name (ex: nova-api): " SONAR_NAME
    done

    while [ -z $SONAR_VERSION ]; do
        read -p "Enter SONAR project version (ex: 0.1.160731): " SONAR_VERSION
    done

}

function set_container_name(){
  if [ -z $CONTAINER_NAME ] && [ -f docker-compose.yml ]; then
    eval $(parse_yaml docker-compose.yml "config_")
    CONTAINER_NAME=${config_services_container_container_name[0]}
  fi
}

function add_phpunit(){
  cat > src/phpunit.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory suffix="Test.php">./tests</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
            <exclude>
                <directory>./app/Console</directory>
                <directory>./app/Events</directory>
                <directory>./app/Jobs</directory>
                <directory>./app/Providers</directory>
                <directory>./app/Exceptions</directory>
                <directory>./app/Http/Request</directory>
                <directory>./app/Http/Middleware</directory>
                <file>./app/Http/Kernel.php</file>
            </exclude>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <ini name="memory_limit" value="512M"/>
    </php>
    <logging>
        <log type="coverage-html" target="./storage/phpunit/" charset="UTF-8" yui="true" highlight="false" lowUpperBound="35" highLowerBound="70"/>
        <log type="coverage-clover" target="./storage/phpunit/codeCoverage.xml"/>
        <log type="junit" target="./storage/phpunit/testResult.xml" logIncompleteSkipped="false"/>
        <log type="testdox-html" target="./storage/phpunit/testdox.html"/>
        <log type="metrics-xml" target="./storage/phpunit/metrics.xml"/>
    </logging>
</phpunit>
EOF
}


function add_sonar(){
  cat > src/sonar-project.properties << EOF
sonar.projectKey=$SONAR_KEY
sonar.projectName=$SONAR_NAME
sonar.projectVersion=$SONAR_VERSION

sonar.sources=app
sonar.tests=tests

sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPath=/var/www/html/storage/phpunit/codeCoverage.xml
sonar.php.tests.reportPath=/var/www/html/storage/phpunit/testResult.xml

sonar.exclusions=app/Http/Kernel.php, app/Providers/**, app/Events/**, app/Console/**, app/Jobs/**, app/Exceptions/**, app/Http/Middleware/**
EOF
}


function add_docker_compose(){
  cat > docker-compose.yml << EOF
version: "2"
services:

  nginx:
    image: nginx:1.11-alpine
    ports:
      - 80:80
    links:
      - container:php
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/var/www/html/

  container:
    image: jaynarol/php-fpm-alpine:7.1-xdebug
    container_name: [wait_container]
    volumes:
      - ./src:/var/www/html/
    environment:
      - APP_KEY=[wait_key]
      - APP_DEBUG=true
      - DB_TEST=true
EOF
}

function add_gitignore(){
  cat > .gitignore << EOF
# Intellij
.idea/
*.iml
*.iws

# Mac
.DS_Store

# me
src/.sonar/
src/storage/phpunit/
EOF
}

function add_nginx_conf(){
  cat > nginx.conf << EOF
worker_processes auto;

events {
    worker_connections  1024;
    multi_accept        on;
}


http {

    sendfile				on;
    tcp_nopush				on;
    tcp_nodelay				on;
    keepalive_timeout			30;
    types_hash_max_size			2048;
    server_tokens			off;
    reset_timedout_connection		on;
    fastcgi_read_timeout		300;

    include				mime.types;
    default_type			text/html;
    access_log				off;
    error_log				off;

    upstream php {
	server php:9000;
    }

    server {

        root		  /var/www/html/public/;
	index		  index.php index.html index.htm;
        charset		  utf-8;

        location / {
            try_files \$uri \$uri/ /index.php?\$query_string;
	}

        location ~ \.php$ {

                include fastcgi.conf;
                fastcgi_intercept_errors on;
                fastcgi_pass php;
        }
    }


}
EOF
}

function parse_yaml() {
    local prefix=$2
    local s
    local w
    local fs
    s='[[:space:]]*'
    w='[a-zA-Z0-9_]*'
    fs="$(echo @|tr @ '\034')"
    sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
    awk -F"$fs" '{
      indent = length($1)/2;
      if (length($2) == 0) { conj[indent]="+";} else {conj[indent]="";}
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
              vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
              printf("%s%s%s%s=(\"%s\")\n", "'"$prefix"'",vn, $2, conj[indent-1],$3);
      }
    }' | sed 's/_=/+=/g'
}

main