#!/bin/bash


function main(){
  clear
  while : ; do
    printf "\n\n[ q:exit | *:test | c:coverage | s:sonar | d:deploy | r:report-project | o:java-doc ]\n\n"
    read -n1 -s
    case "$REPLY" in\
	"r") clear; project_report                            ;; 
	"c") clear; coverage_report                           ;; 
	"s") clear; mvn sonar:sonar                           ;; 
	"d") clear; deploy                                    ;; 
	"o") clear; java_doc                                  ;; 
	"q") break                                            ;; 
	 * ) clear; mvn clean test                            ;; 
    esac
  done
}

function deploy(){
    cmd "/c mvn deploy"
}

function project_report(){
    mvn clean test site
    start target/site/index.html
}

function coverage_report(){
    mvn cobertura:cobertura
    start target/site/cobertura/index.html
}

function java_doc(){
    mvn javadoc:javadoc
    start target/site/apidocs/index.html
}


main