#!/bin/bash


function main(){
  clear
  while : ; do
    printf "\n\n[ q:exit | *:test | c:coverage | s:sonar | d:deploy | p:package | r:report-project | o:java-doc ]\n\n"
    read -n1 -s
    case "$REPLY" in\
	"r") clear; project_report        ;; 
	"c") clear; coverage_report       ;; 
	"s") clear; sonar                 ;; 
	"d") clear; deploy                ;; 
	"o") clear; java_doc              ;; 
	"p") clear; package               ;; 
	"q") break                        ;; 
	 * ) clear; mvn clean test        ;; 
    esac
  done
}

function sonar(){
    mvn clean test sonar:sonar
}

function deploy(){
    mvn clean test deploy
}

function package(){
    rm -rf ./jar
    mvn clean test package
}


function project_report(){
    mvn clean test site
    start target/site/index.html
}

function coverage_report(){
    mvn clean test cobertura:cobertura
    start target/site/cobertura/index.html
}

function java_doc(){
    mvn clean test javadoc:javadoc
    start target/site/apidocs/index.html
}

main