#!/bin/bash


function main(){
  clear
  while : ; do
cat << EOF

q) Exit
1) Remove [EXITED] Container
2) Remove [DANGLING] Image
3) Remove [DANGLING] Volume

i) Remove [ALL] Image
c) Remove [ALL] Container

EOF
echo "Select your choice :"
    read -n1 -s
    case "$REPLY" in\
	 1 ) clear; docker ps -a --no-trunc | egrep 'Exited' | awk '{print $1}' | xargs --no-run-if-empty docker rm -f  ;; 
	 2 ) clear; docker rmi -f $(docker images -qf dangling=true)        ;; 
	 3 ) clear; docker volume rm $(docker volume ls -qf dangling=true)     ;; 
	 i ) clear; docker rmi -f $(docker images -q)       ;; 
	 c ) clear; docker rm -f $(docker ps -aq)     ;; 
	"q") break                      ;; 
    esac
  done
}

main