#!/bin/bash

while : ; do

  read -p "[composer] : " COMMAND
  
  case "$COMMAND" in
    "exit") clear; break  ;; 
     * ) docker run --rm -v /$(pwd)/:/app composer/composer $COMMAND ;; 
  esac

done